import { ThemeProvider } from "@/app/_components/theme-provider";
import type { Metadata } from "next";
import "./globals.css";
import Navbar from "@/app/_components/navbar";
import { FirebaseProvider } from "@/app/context/articleContext";
import { Toaster } from "@/components/ui/toaster";
import { AuthProvider } from "@/app/context/authContext";
import { Inter, Bebas_Neue } from 'next/font/google';

const inter = Inter({
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-inter',
});

const heading = Bebas_Neue({
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-heading',
  weight: '400',
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="fr" suppressHydrationWarning className={`${inter.variable} ${heading.variable}`}>
      <body suppressHydrationWarning>
        <AuthProvider>
          <FirebaseProvider>
            <ThemeProvider
              attribute="class"
              defaultTheme="system"
              enableSystem
              disableTransitionOnChange
            >
              <Navbar />
              {children}
            </ThemeProvider>
            <Toaster />
          </FirebaseProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
