import { ThemeProvider } from "@/app/components/theme-provider";
import type { Metadata } from "next";
import "./globals.css";
import Navbar from "@/app/components/navbar";
import { FirebaseProvider } from "@/app/context/articleContext";

import { Toaster } from "@/components/ui/toaster";
import { AuthProvider } from "@/app/context/authContext";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="fr" suppressHydrationWarning>
      <body suppressHydrationWarning>
        <AuthProvider>
          <FirebaseProvider>
            <ThemeProvider
              attribute="class"
              defaultTheme="system"
              enableSystem
              disableTransitionOnChange
            >
              <Navbar />
              {children}
            </ThemeProvider>
            <Toaster />
          </FirebaseProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
